# Modal 与消息内容限制，统一供界面、业务校验和测试使用。
STRUCTURED_SPEECH_MODAL_TIMEOUT_SECONDS = 30 * 60
STRUCTURED_SPEECH_MAX_ATTACHMENTS = 5
STRUCTURED_SPEECH_FIELD_MAX_LENGTH = 1800
STRUCTURED_SPEECH_MESSAGE_MAX_LENGTH = 2000

# Discord 帖子慢速模式和 Bot 内部用户冷却的默认规则。
STRUCTURED_SPEECH_SLOWMODE_SECONDS = 10 * 60
STRUCTURED_SPEECH_DEFAULT_INTERVAL_SECONDS = 2 * 60
STRUCTURED_SPEECH_MIN_INTERVAL_MINUTES = 1
STRUCTURED_SPEECH_MAX_INTERVAL_MINUTES = 60

# 论坛级 Webhook 使用固定名称，以便重启后安全复用。
STRUCTURED_SPEECH_WEBHOOK_NAME = "StellariaPact 结构化发言"
STRUCTURED_SPEECH_REPLY_CONTEXT_MENU_NAME = "提案发言(回复)"

# 持久化状态包含过渡态，用于在进程意外退出后恢复未完成的切换。
STRUCTURED_SPEECH_STATUS_INACTIVE = "inactive"
STRUCTURED_SPEECH_STATUS_ENABLING = "enabling"
STRUCTURED_SPEECH_STATUS_ACTIVE = "active"
STRUCTURED_SPEECH_STATUS_DISABLING = "disabling"

# 治理角色可管理模式，并豁免 Bot 内部的发言冷却和直接发言拦截。
GOVERNANCE_ROLE_KEYS = ("stewards", "councilModerator", "executionAuditor")
