"""add ConfirmationSession reason

Revision ID: 00a6cd83f4bf
Revises: a0f82ed106da
Create Date: 2025-12-09 23:38:24.629909

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '00a6cd83f4bf'
down_revision: Union[str, Sequence[str], None] = 'a0f82ed106da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmation_session', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('confirmation_session', 'reason')
    # ### end Alembic commands ###
