"""Create a new proposal vote

Revision ID: 68ae4e95b903
Revises: 1ac855605faf
Create Date: 2026-03-21 18:45:24.625206

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '68ae4e95b903'
down_revision: Union[str, Sequence[str], None] = '1ac855605faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote_message_mirror',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vote_message_mirror_channel_id'), 'vote_message_mirror', ['channel_id'], unique=False)
    op.create_index(op.f('ix_vote_message_mirror_guild_id'), 'vote_message_mirror', ['guild_id'], unique=False)
    op.create_index(op.f('ix_vote_message_mirror_message_id'), 'vote_message_mirror', ['message_id'], unique=False)
    op.create_index(op.f('ix_vote_message_mirror_session_id'), 'vote_message_mirror', ['session_id'], unique=False)
    op.drop_index(op.f('ix_objection_objectionThreadId'), table_name='objection')
    op.drop_index(op.f('ix_objection_objectorId'), table_name='objection')
    op.drop_index(op.f('ix_objection_proposalId'), table_name='objection')
    op.drop_index(op.f('ix_objection_reviewThreadId'), table_name='objection')
    op.create_index(op.f('ix_objection_objection_thread_id'), 'objection', ['objection_thread_id'], unique=False)
    op.create_index(op.f('ix_objection_objector_id'), 'objection', ['objector_id'], unique=False)
    op.create_index(op.f('ix_objection_proposal_id'), 'objection', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_objection_review_thread_id'), 'objection', ['review_thread_id'], unique=False)
    op.drop_index(op.f('ix_proposal_proposerId'), table_name='proposal')
    op.create_index(op.f('ix_proposal_proposer_id'), 'proposal', ['proposer_id'], unique=False)
    op.add_column('vote_session', sa.Column('max_choices_per_user', sa.Integer(), nullable=False, server_default='999999'))
    op.add_column('vote_session', sa.Column('ui_style', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote_session', 'ui_style')
    op.drop_column('vote_session', 'max_choices_per_user')
    op.drop_index(op.f('ix_proposal_proposer_id'), table_name='proposal')
    op.create_index(op.f('ix_proposal_proposerId'), 'proposal', ['proposer_id'], unique=False)
    op.drop_index(op.f('ix_objection_review_thread_id'), table_name='objection')
    op.drop_index(op.f('ix_objection_proposal_id'), table_name='objection')
    op.drop_index(op.f('ix_objection_objector_id'), table_name='objection')
    op.drop_index(op.f('ix_objection_objection_thread_id'), table_name='objection')
    op.create_index(op.f('ix_objection_reviewThreadId'), 'objection', ['review_thread_id'], unique=False)
    op.create_index(op.f('ix_objection_proposalId'), 'objection', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_objection_objectorId'), 'objection', ['objector_id'], unique=False)
    op.create_index(op.f('ix_objection_objectionThreadId'), 'objection', ['objection_thread_id'], unique=False)
    op.drop_index(op.f('ix_vote_message_mirror_session_id'), table_name='vote_message_mirror')
    op.drop_index(op.f('ix_vote_message_mirror_message_id'), table_name='vote_message_mirror')
    op.drop_index(op.f('ix_vote_message_mirror_guild_id'), table_name='vote_message_mirror')
    op.drop_index(op.f('ix_vote_message_mirror_channel_id'), table_name='vote_message_mirror')
    op.drop_table('vote_message_mirror')
    # ### end Alembic commands ###
