"""Upgrade schema to support new features

Revision ID: 6bfbafb142c0
Revises:
Create Date: 2025-11-01 22:49:02.369999

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bfbafb142c0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("proposal", sa.Column("content", sa.String(), nullable=False, server_default=""))
    op.add_column("votesession", sa.Column("votingChannelMessageId", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_votesession_votingChannelMessageId"),
        "votesession",
        ["votingChannelMessageId"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_votesession_votingChannelMessageId"), table_name="votesession")
    op.drop_column("votesession", "votingChannelMessageId")
    op.drop_column("proposal", "content")
    # ### end Alembic commands ###
