"""refactor and add multi vote
Revision ID: a0f82ed106da
Revises: 6bfbafb142c0
Create Date: 2025-11-20 18:24:31.680407
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0f82ed106da"
down_revision: Union[str, Sequence[str], None] = "6bfbafb142c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new table for vote options
    op.create_table(
        "vote_option",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("choice_index", sa.Integer(), nullable=False),
        sa.Column("choice_text", sqlmodel.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "choice_index", name="uk_voteoption_session_choice"),
    )
    op.create_index(op.f("ix_vote_option_session_id"), "vote_option", ["session_id"], unique=False)

    with op.batch_alter_table("announcement", schema=None) as batch_op:
        batch_op.alter_column("discussionThreadId", new_column_name="discussion_thread_id")
        batch_op.alter_column("announcerId", new_column_name="announcer_id")
        batch_op.alter_column("endTime", new_column_name="end_time")
        batch_op.alter_column("autoExecute", new_column_name="auto_execute")
        batch_op.alter_column("createdAt", new_column_name="created_at")

    with op.batch_alter_table("announcementchannelmonitor", schema=None) as batch_op:
        batch_op.alter_column("announcementId", new_column_name="announcement_id")
        batch_op.alter_column("channelId", new_column_name="channel_id")
        batch_op.alter_column("messageThreshold", new_column_name="message_threshold")
        batch_op.alter_column("timeIntervalMinutes", new_column_name="time_interval_minutes")
        batch_op.alter_column("messageCountSinceLast", new_column_name="message_count_since_last")
        batch_op.alter_column("lastRepostAt", new_column_name="last_repost_at")

    with op.batch_alter_table("confirmationsession", schema=None) as batch_op:
        batch_op.alter_column("targetId", new_column_name="target_id")
        batch_op.alter_column("messageId", new_column_name="message_id")
        batch_op.alter_column("requiredRoles", new_column_name="required_roles")
        batch_op.alter_column("confirmedParties", new_column_name="confirmed_parties")
        batch_op.alter_column("cancelerId", new_column_name="canceler_id")
        batch_op.alter_column("createdAt", new_column_name="created_at")
        batch_op.alter_column("updatedAt", new_column_name="updated_at")

    with op.batch_alter_table("objection", schema=None) as batch_op:
        batch_op.alter_column("proposalId", new_column_name="proposal_id")
        batch_op.alter_column("objectorId", new_column_name="objector_id")
        batch_op.alter_column("objectionThreadId", new_column_name="objection_thread_id")
        batch_op.alter_column("reviewThreadId", new_column_name="review_thread_id")
        batch_op.alter_column("requiredVotes", new_column_name="required_votes")
        batch_op.alter_column("createdAt", new_column_name="created_at")

    with op.batch_alter_table("proposal", schema=None) as batch_op:
        batch_op.alter_column("discussionThreadId", new_column_name="discussion_thread_id")
        batch_op.alter_column("proposerId", new_column_name="proposer_id")
        batch_op.alter_column("createdAt", new_column_name="created_at")
        batch_op.alter_column("updatedAt", new_column_name="updated_at")

    with op.batch_alter_table("useractivity", schema=None) as batch_op:
        batch_op.alter_column("userId", new_column_name="user_id")
        batch_op.alter_column("contextThreadId", new_column_name="context_thread_id")
        batch_op.alter_column("messageCount", new_column_name="message_count")
        batch_op.alter_column("muteEndTime", new_column_name="mute_end_time")
        batch_op.alter_column("lastUpdated", new_column_name="last_updated")

    with op.batch_alter_table("uservote", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("choice_index", sa.Integer(), nullable=False, server_default="1")
        )
        batch_op.alter_column("sessionId", new_column_name="session_id")
        batch_op.alter_column("userId", new_column_name="user_id")
        batch_op.alter_column("votedAt", new_column_name="voted_at")
        batch_op.drop_constraint("unique_user_vote_per_session", type_="unique")
        batch_op.create_unique_constraint(
            "uk_user_vote_option", ["session_id", "user_id", "choice_index"]
        )

    with op.batch_alter_table("votesession", schema=None) as batch_op:
        batch_op.add_column(sa.Column("guild_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("total_choices", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.alter_column("contextThreadId", new_column_name="context_thread_id")
        batch_op.alter_column("objectionId", new_column_name="objection_id")
        batch_op.alter_column("contextMessageId", new_column_name="context_message_id")
        batch_op.alter_column(
            "votingChannelMessageId", new_column_name="voting_channel_message_id"
        )
        batch_op.alter_column("anonymousFlag", new_column_name="anonymous_flag")
        batch_op.alter_column("realtimeFlag", new_column_name="realtime_flag")
        batch_op.alter_column("notifyFlag", new_column_name="notify_flag")
        batch_op.alter_column("endTime", new_column_name="end_time")
        batch_op.alter_column("createdAt", new_column_name="created_at")

    # Set default guild_id for existing vote_session records
    op.execute("UPDATE votesession SET guild_id = 1134557553011998840 WHERE guild_id IS NULL")

    # Rename tables to snake_case
    op.rename_table("announcementchannelmonitor", "announcement_channel_monitor")
    op.rename_table("confirmationsession", "confirmation_session")
    op.rename_table("useractivity", "user_activity")
    op.rename_table("uservote", "user_vote")
    op.rename_table("votesession", "vote_session")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop table 'vote_option'
    op.drop_index(op.f("ix_vote_option_session_id"), table_name="vote_option")
    op.drop_table("vote_option")

    with op.batch_alter_table("announcement", schema=None) as batch_op:
        batch_op.alter_column("discussion_thread_id", new_column_name="discussionThreadId")
        batch_op.alter_column("announcer_id", new_column_name="announcerId")
        batch_op.alter_column("end_time", new_column_name="endTime")
        batch_op.alter_column("auto_execute", new_column_name="autoExecute")
        batch_op.alter_column("created_at", new_column_name="createdAt")

    with op.batch_alter_table("announcementchannelmonitor", schema=None) as batch_op:
        batch_op.alter_column("announcement_id", new_column_name="announcementId")
        batch_op.alter_column("channel_id", new_column_name="channelId")
        batch_op.alter_column("message_threshold", new_column_name="messageThreshold")
        batch_op.alter_column("time_interval_minutes", new_column_name="timeIntervalMinutes")
        batch_op.alter_column("message_count_since_last", new_column_name="messageCountSinceLast")
        batch_op.alter_column("last_repost_at", new_column_name="lastRepostAt")

    with op.batch_alter_table("confirmationsession", schema=None) as batch_op:
        batch_op.alter_column("target_id", new_column_name="targetId")
        batch_op.alter_column("message_id", new_column_name="messageId")
        batch_op.alter_column("required_roles", new_column_name="requiredRoles")
        batch_op.alter_column("confirmed_parties", new_column_name="confirmedParties")
        batch_op.alter_column("canceler_id", new_column_name="cancelerId")
        batch_op.alter_column("created_at", new_column_name="createdAt")
        batch_op.alter_column("updated_at", new_column_name="updatedAt")

    with op.batch_alter_table("objection", schema=None) as batch_op:
        batch_op.alter_column("proposal_id", new_column_name="proposalId")
        batch_op.alter_column("objector_id", new_column_name="objectorId")
        batch_op.alter_column("objection_thread_id", new_column_name="objectionThreadId")
        batch_op.alter_column("review_thread_id", new_column_name="reviewThreadId")
        batch_op.alter_column("required_votes", new_column_name="requiredVotes")
        batch_op.alter_column("created_at", new_column_name="createdAt")

    with op.batch_alter_table("proposal", schema=None) as batch_op:
        batch_op.alter_column("discussion_thread_id", new_column_name="discussionThreadId")
        batch_op.alter_column("proposer_id", new_column_name="proposerId")
        batch_op.alter_column("created_at", new_column_name="createdAt")
        batch_op.alter_column("updated_at", new_column_name="updatedAt")

    with op.batch_alter_table("useractivity", schema=None) as batch_op:
        batch_op.alter_column("user_id", new_column_name="userId")
        batch_op.alter_column("context_thread_id", new_column_name="contextThreadId")
        batch_op.alter_column("message_count", new_column_name="messageCount")
        batch_op.alter_column("mute_end_time", new_column_name="muteEndTime")
        batch_op.alter_column("last_updated", new_column_name="lastUpdated")

    with op.batch_alter_table("user_vote", schema=None) as batch_op:
        batch_op.drop_constraint("uk_user_vote_option", type_="unique")
        batch_op.create_unique_constraint(
            "unique_user_vote_per_session", ["session_id", "user_id"]
        )
        batch_op.drop_column("choice_index")
        batch_op.alter_column("session_id", new_column_name="sessionId")
        batch_op.alter_column("user_id", new_column_name="userId")
        batch_op.alter_column("voted_at", new_column_name="votedAt")

    with op.batch_alter_table("vote_session", schema=None) as batch_op:
        batch_op.drop_column("guild_id")
        batch_op.drop_column("total_choices")
        batch_op.alter_column("context_thread_id", new_column_name="contextThreadId")
        batch_op.alter_column("objection_id", new_column_name="objectionId")
        batch_op.alter_column("context_message_id", new_column_name="contextMessageId")
        batch_op.alter_column(
            "voting_channel_message_id", new_column_name="votingChannelMessageId"
        )
        batch_op.alter_column("anonymous_flag", new_column_name="anonymousFlag")
        batch_op.alter_column("realtime_flag", new_column_name="realtimeFlag")
        batch_op.alter_column("notify_flag", new_column_name="notifyFlag")
        batch_op.alter_column("end_time", new_column_name="endTime")
        batch_op.alter_column("created_at", new_column_name="createdAt")

    # Revert table renames from snake_case
    op.rename_table("vote_session", "votesession")
    op.rename_table("user_vote", "uservote")
    op.rename_table("user_activity", "useractivity")
    op.rename_table("confirmation_session", "confirmationsession")
    op.rename_table("announcement_channel_monitor", "announcementchannelmonitor")
    # ### end Alembic commands ###
